# Generated by Django 5.2 on 2025-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="appointments",
                to="appointments.tag",
                verbose_name="Tags",
            ),
        ),
    ]
