# Generated by Django 5.2 on 2025-04-03 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date"], "verbose_name": "Appointment"},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Datetime"
            ),
        ),
    ]
